import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "./providers";
import "./globals.css";

const inter = localFont({
	src: "../public/fonts/Inter_Variable.ttf",
	variable: "--font-inter",
	display: "swap",
	preload: true,
});

const bricolage = localFont({
	src: [
		{
			path: "../public/fonts/BricolageGrotesqueCondensedRegular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/BricolageGrotesqueCondensedBold.ttf",
			weight: "700",
			style: "normal",
		},
	],
	variable: "--font-bricolage-grotesque",
	display: "swap",
	preload: true,
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${inter.variable} ${bricolage.variable}`}>
			<body className="antialiased">
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
