import type { Metadata } from "next";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";
import type { VariantKey } from "@/config";
import "./globals.css";

const inter = localFont({
  src: "../public/fonts/Inter_Variable.ttf",
  variable: "--font-inter",
  display: "swap",
  preload: true,
});

const bricolage = localFont({
  src: [
    {
      path: "../public/fonts/BricolageGrotesqueCondensedRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/BricolageGrotesqueCondensedBold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-bricolage-grotesque",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const raw = cookieStore.get("nostrum_variant")?.value;
  const variant: VariantKey = raw === "a" || raw === "b" ? raw : "a";

  return (
    <html lang="en" className={`${inter.variable} ${bricolage.variable}`}>
      <body className="antialiased">
        <Providers variant={variant}>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
