export { DevisVariantA } from "./variant-a";
export { DevisVariantB } from "./variant-b";
export { GarantiesVariantA } from "./garanties-variant-a";
export { GarantiesVariantB } from "./garanties-variant-b";
export { ComparateurVariantA } from "./comparateur-variant-a";
export { ComparateurVariantB } from "./comparateur-variant-b";
export { ComparateurWelcome as ComparateurWelcomeVariantA } from "./comparateur-a-welcome";
export { OptionsVariantA } from "./options-variant-a";
export { OptionsVariantB } from "./options-variant-b";
export { RecapVariantA } from "./recap-variant-a";
